### ISSUE TITLE
I found that it is not the same as the official webhook.

### ISSUE THREAD

**Issue by Alubba** [synconics/odoo-webhook#2]
Hi,

Depends on your documentation, it is a lot of differences between official web hook and documentation.
Could you please give me some advice so that I can proceed to use the web hook?

Thanks,
Michael

**Comment by synconics** [comment]
Hi Michael,

We just published Odoo webhook module on the Odoo apps store, kindly go through this link:

https://www.odoo.com/apps/modules/11.0/webhooks/

Best regards,
Team Synconics
